services:
  mcp-everything:
    build:
      context: ../
      dockerfile: ./mcp-everything/Dockerfile
    container_name: mcp-everything
    restart: unless-stopped
    networks:
      - public
    expose:
      - "3000"
    environment:
      - MCP_PROTOCOL_VERSION=${MCP_PROTOCOL_VERSION:-2025-06-18}
      - BASE_DOMAIN=${BASE_DOMAIN}
    # HTTP health check - verifies streamableHttp can initialize successfully
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -X POST http://localhost:3000/mcp -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' -d '{\"jsonrpc\":\"2.0\",\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\",\"capabilities\":{},\"clientInfo\":{\"name\":\"healthcheck\",\"version\":\"1.0\"}},\"id\":1}' | grep -q '\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\"'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
