# 🔥 Sacred Pre-commit Configuration - The Divine Git Guardian! ⚡
# Prevents deprecated patterns and ensures code quality before commits

repos:
  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        description: "🔥 Ruff linting with auto-fix"
      
      # Run the formatter  
      - id: ruff-format
        description: "⚡ Ruff code formatting"

  # Custom Pydantic deprecation hunting
  - repo: local
    hooks:
      - id: pydantic-compliance
        name: "🔥 Pydantic Deprecation Hunter"
        entry: python scripts/lint_pydantic_compliance.py
        language: system
        types: [python]
        description: "Hunt deprecated Pydantic v1 syntax"
        pass_filenames: false
        
  # Ensure Python files end with newline
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        description: "Ensure files end with newline"
      
      - id: trailing-whitespace
        description: "Remove trailing whitespace"
      
      - id: check-yaml
        description: "Check YAML syntax"
      
      - id: check-toml
        description: "Check TOML syntax"
      
      - id: check-json
        description: "Check JSON syntax"
        
      - id: check-merge-conflict
        description: "Check for merge conflict markers"
        
      - id: check-added-large-files
        description: "Prevent large files from being committed"
        args: ['--maxkb=1000']

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        description: "🔒 Security vulnerability scanning"
        exclude: ^tests/

# Global configuration
default_stages: [commit]
fail_fast: false

# CI configuration
ci:
  autofix_commit_msg: |
    🔥 [pre-commit.ci] Auto-fix sacred code quality violations ⚡
    
    Co-Authored-By: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
  autofix_prs: true
  autoupdate_commit_msg: |
    ⚡ [pre-commit.ci] Update divine linting tools ⚡
    
    Co-Authored-By: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
  autoupdate_schedule: weekly