# The root orchestrator that unites the three divine realms
# Each service maintains its own docker-compose.yml for sacred isolation

include:
  - traefik/docker-compose.yml
  - auth/docker-compose.yml
  - mcp-echo/docker-compose.yml
  - mcp-fetch/docker-compose.yml
  - mcp-filesystem/docker-compose.yml
  - mcp-fetchs/docker-compose.yml
  - mcp-everything/docker-compose.yml
  - mcp-memory/docker-compose.yml
  - mcp-sequentialthinking/docker-compose.yml
  - mcp-time/docker-compose.yml
  - mcp-tmux/docker-compose.yml
  - mcp-playwright/docker-compose.yml

# Shared middleware definitions accessible to all services
services:
  # This is a dummy service that only defines shared middlewares
  # It uses the smallest possible image and stays running to maintain middleware definitions
  shared-middlewares:
    image: busybox:latest
    container_name: shared-middlewares
    command: ["sleep", "infinity"]  # Stay running to maintain middleware definitions
    restart: unless-stopped
    networks:
      - public
    labels:
      - "traefik.enable=false"  # Middlewares now defined in auth service
      - "traefik.http.services.shared-middlewares.loadbalancer.server.port=1234"  # Dummy port (service not routed to)

      # NOTE: Middleware definitions moved to auth/docker-compose.yml to avoid conflicts

      # Shared HTTPS redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  public:
    external: true

volumes:
  traefik-certificates:
    external: true
  redis-data:
    external: true
  coverage-data:
    external: true
  auth-keys:
    external: true
  mcp-memory-data:
    external: true
