services:
  mcp-fetchs:
    build:
      context: ../
      dockerfile: mcp-fetchs/Dockerfile
    container_name: mcp-fetchs
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - MCP_SERVER_NAME=mcp-fetch-streamablehttp
      - MCP_SERVER_VERSION=0.1.0
      - MCP_PROTOCOL_VERSION=${MCP_PROTOCOL_VERSION:-2025-06-18}
      - MCP_FETCH_DEFAULT_USER_AGENT=ModelContextProtocol/1.0 (Fetch Server)
    networks:
      - public
    labels:
      # Basic router
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      
      # CORS preflight (OPTIONS) endpoint - no auth - higher priority
      - "traefik.http.routers.mcp-fetchs-options.rule=Host(`fetchs.${BASE_DOMAIN}`) && PathPrefix(`/mcp`) && Method(`OPTIONS`)"
      - "traefik.http.routers.mcp-fetchs-options.priority=3"
      - "traefik.http.routers.mcp-fetchs-options.service=mcp-fetchs"
      - "traefik.http.routers.mcp-fetchs-options.tls=true"
      - "traefik.http.routers.mcp-fetchs-options.tls.certresolver=letsencrypt"
      
      # MCP endpoint with auth - lower priority catches all non-OPTIONS
      - "traefik.http.routers.mcp-fetchs.rule=Host(`fetchs.${BASE_DOMAIN}`) && PathPrefix(`/mcp`)"
      - "traefik.http.routers.mcp-fetchs.priority=2"
      - "traefik.http.routers.mcp-fetchs.middlewares=mcp-auth@docker,mcp-cors@docker"
      - "traefik.http.routers.mcp-fetchs.service=mcp-fetchs"
      - "traefik.http.routers.mcp-fetchs.tls=true"
      - "traefik.http.routers.mcp-fetchs.tls.certresolver=letsencrypt"
      
      # OAuth discovery endpoint
      - "traefik.http.routers.mcp-fetchs-oauth-discovery.rule=Host(`fetchs.${BASE_DOMAIN}`) && PathPrefix(`/.well-known/oauth-authorization-server`)"
      - "traefik.http.routers.mcp-fetchs-oauth-discovery.priority=10"
      - "traefik.http.routers.mcp-fetchs-oauth-discovery.service=auth@docker"
      - "traefik.http.routers.mcp-fetchs-oauth-discovery.middlewares=oauth-discovery-rewrite"
      - "traefik.http.routers.mcp-fetchs-oauth-discovery.tls=true"
      - "traefik.http.routers.mcp-fetchs-oauth-discovery.tls.certresolver=letsencrypt"
      
      
      # Service definition
      - "traefik.http.services.mcp-fetchs.loadbalancer.server.port=3000"
      
      # Middleware for OAuth discovery
      - "traefik.http.middlewares.oauth-discovery-rewrite.headers.customrequestheaders.Host=auth.${BASE_DOMAIN}"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -X POST http://localhost:3000/mcp -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' -d '{\"jsonrpc\":\"2.0\",\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\",\"capabilities\":{},\"clientInfo\":{\"name\":\"healthcheck\",\"version\":\"1.0\"}},\"id\":1}' | grep -q '\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\"'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  public:
    external: true