services:
  mcp-fetch:
    build:
      context: ../
      dockerfile: mcp-fetch/Dockerfile
    container_name: mcp-fetch
    restart: unless-stopped
    networks:
      - public
    environment:
      - MCP_CORS_ORIGINS=${MCP_CORS_ORIGINS}
      - MCP_PROTOCOL_VERSION=2025-03-26
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mcp-fetch.loadbalancer.server.port=3000"
      
      # OAuth discovery route - Priority 10 (ABSOLUTE HIGHEST - must work without auth!)
      - "traefik.http.routers.mcp-fetch-oauth-discovery.rule=Host(`fetch.${BASE_DOMAIN}`) && PathPrefix(`/.well-known/oauth-authorization-server`)"
      - "traefik.http.routers.mcp-fetch-oauth-discovery.priority=10"
      - "traefik.http.routers.mcp-fetch-oauth-discovery.entrypoints=websecure"
      - "traefik.http.routers.mcp-fetch-oauth-discovery.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mcp-fetch-oauth-discovery.middlewares=oauth-discovery-rewrite@docker"
      - "traefik.http.routers.mcp-fetch-oauth-discovery.service=auth@docker"
      # No auth middleware - OAuth discovery must be public!
      
      # Middleware to rewrite host header for auth service
      - "traefik.http.middlewares.oauth-discovery-rewrite.headers.customrequestheaders.Host=auth.${BASE_DOMAIN}"
      
      # CORS preflight route (OPTIONS) - Priority 4 (HIGHEST for OPTIONS)
      - "traefik.http.routers.mcp-fetch-cors.rule=Host(`fetch.${BASE_DOMAIN}`) && Method(`OPTIONS`)"
      - "traefik.http.routers.mcp-fetch-cors.priority=4"
      - "traefik.http.routers.mcp-fetch-cors.entrypoints=websecure"
      - "traefik.http.routers.mcp-fetch-cors.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mcp-fetch-cors.service=mcp-fetch"
      # No auth middleware for CORS preflight!
      
      # MCP route with auth - Priority 2
      # Use PathPrefix to handle both /mcp and /mcp/
      - "traefik.http.routers.mcp-fetch.rule=Host(`fetch.${BASE_DOMAIN}`) && PathPrefix(`/mcp`)"
      - "traefik.http.routers.mcp-fetch.priority=2"
      - "traefik.http.routers.mcp-fetch.entrypoints=websecure"
      - "traefik.http.routers.mcp-fetch.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mcp-fetch.middlewares=mcp-auth@docker,mcp-cors@docker"
      - "traefik.http.routers.mcp-fetch.service=mcp-fetch"
      
      # Catch-all route with auth - Priority 1 (LOWEST for HTTPS)
      - "traefik.http.routers.mcp-fetch-catchall.rule=Host(`fetch.${BASE_DOMAIN}`)"
      - "traefik.http.routers.mcp-fetch-catchall.priority=1"
      - "traefik.http.routers.mcp-fetch-catchall.entrypoints=websecure"
      - "traefik.http.routers.mcp-fetch-catchall.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mcp-fetch-catchall.middlewares=mcp-auth@docker,mcp-cors@docker"
      - "traefik.http.routers.mcp-fetch-catchall.service=mcp-fetch"
      
      # HTTP to HTTPS redirect for MCP service - Priority 1 (same as catchall but for HTTP)
      - "traefik.http.routers.mcp-fetch-redirect.rule=Host(`fetch.${BASE_DOMAIN}`)"
      - "traefik.http.routers.mcp-fetch-redirect.entrypoints=web"
      - "traefik.http.routers.mcp-fetch-redirect.middlewares=redirect-to-https"
      - "traefik.http.routers.mcp-fetch-redirect.priority=1"
      - "traefik.http.routers.mcp-fetch-redirect.service=mcp-fetch"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -X POST http://localhost:3000/mcp -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' -d '{\"jsonrpc\":\"2.0\",\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\",\"capabilities\":{},\"clientInfo\":{\"name\":\"healthcheck\",\"version\":\"1.0\"}},\"id\":1}' | grep -q '\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\"'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  public:
    external: true