services:
  mcp-time:
    build:
      context: ../
      dockerfile: mcp-time/Dockerfile
    container_name: mcp-time
    restart: unless-stopped
    networks:
      - public
    environment:
      - MCP_CORS_ORIGINS=*
      - MCP_PROTOCOL_VERSION=2025-03-26
    labels:
      # OAuth Discovery Route - Priority 10 (Highest!)
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-time-oauth-discovery.rule=Host(`time.${BASE_DOMAIN}`) && PathPrefix(`/.well-known/oauth-authorization-server`)"
      - "traefik.http.routers.mcp-time-oauth-discovery.priority=10"
      - "traefik.http.routers.mcp-time-oauth-discovery.service=auth@docker"
      - "traefik.http.routers.mcp-time-oauth-discovery.tls=true"
      - "traefik.http.routers.mcp-time-oauth-discovery.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.mcp-time-oauth-discovery-rewrite.headers.customrequestheaders.Host=auth.${BASE_DOMAIN}"
      - "traefik.http.routers.mcp-time-oauth-discovery.middlewares=mcp-time-oauth-discovery-rewrite"

      # CORS Preflight Route - Priority 6
      - "traefik.http.routers.mcp-time-cors.rule=Host(`time.${BASE_DOMAIN}`) && Method(`OPTIONS`)"
      - "traefik.http.routers.mcp-time-cors.priority=6"
      - "traefik.http.routers.mcp-time-cors.service=mcp-time"
      - "traefik.http.routers.mcp-time-cors.tls=true"
      - "traefik.http.routers.mcp-time-cors.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mcp-time-cors.middlewares=mcp-cors@file"

      # MCP Route with Auth - Priority 2
      - "traefik.http.routers.mcp-time.rule=Host(`time.${BASE_DOMAIN}`) && PathPrefix(`/mcp`)"
      - "traefik.http.routers.mcp-time.priority=2"
      - "traefik.http.routers.mcp-time.service=mcp-time"
      - "traefik.http.routers.mcp-time.tls=true"
      - "traefik.http.routers.mcp-time.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mcp-time.middlewares=mcp-cors@file,mcp-auth@file"

      # Catch-all Route with Auth - Priority 1 (Lowest!)
      - "traefik.http.routers.mcp-time-catchall.rule=Host(`time.${BASE_DOMAIN}`)"
      - "traefik.http.routers.mcp-time-catchall.priority=1"
      - "traefik.http.routers.mcp-time-catchall.service=mcp-time"
      - "traefik.http.routers.mcp-time-catchall.tls=true"
      - "traefik.http.routers.mcp-time-catchall.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mcp-time-catchall.middlewares=mcp-cors@file,mcp-auth@file"

      # Service definition
      - "traefik.http.services.mcp-time.loadbalancer.server.port=3000"

    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -X POST http://localhost:3000/mcp -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' -d '{\"jsonrpc\":\"2.0\",\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\",\"capabilities\":{},\"clientInfo\":{\"name\":\"healthcheck\",\"version\":\"1.0\"}},\"id\":1}' | grep -q '\"protocolVersion\":\"'$$MCP_PROTOCOL_VERSION'\"'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  public:
    external: true
